### PR TITLE
Allow builds against master

### PR DESCRIPTION
**Pull request by jseely**
These changes make it possible for users to build against master.

### CODE REVIEW

**Comment by vcabbage** [comment]
Can you explain the problem you're running into? I can likely help you sort it out.

The name of this package is "pack.ag/amqp", I'm not going to be changing that.

**Comment by jseely** [comment]
There are fixes in the master branch of this project to bugs I'm running into. It doesn't look like these have been pushed to the `pack.ag` repo so the only way to build against this repo is to make these changes.

It looks like the only references to `pack.ag` are in the tests, is there any way to remove these so if someone wants to build against the latest code they can?

**Comment by vcabbage** [comment]
pack.ag/amqp isn't a separate repo. It's just an HTML page that serves metadata which tells `go get` to pull from this repo.

Running `go get -u pack.ag/amqp` should pull the latest master. Some vendoring tools default to the latest tagged release. I just tagged a new release in case that's what you were running into.

**Comment by vcabbage** [comment]
Yeah, more or less. I like having a "vanity domain" for my projects and there are hypothetical advantages if I ever wanted to move a project under and organization account or to a different hosting platform.

Assuming you were able to get the latest master, I'm going to go ahead an close the PR. Let me know if you run into in any other issues.

**Pull request closed without merging**
