### PR TITLE
Validate received transfers adhere to the spec

### PR DESCRIPTION
**Pull request by vcabbage**
Updates #161

### CODE REVIEW

**Comment by vcabbage** [comment]
@devigned It seems Event Hubs don't include a delivery-tag in transfers.

The spec says:
> Each delivery MUST be identified by a delivery-tag chosen by the sending application. The delivery-tag MUST be unique amongst all deliveries that could be considered unsettled by either end of the link. 

http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-transport-v1.0.html#doc-idp438000

The transfer section is less clear:
> This field MUST be specified for the first transfer of a multi-transfer message and can only be omitted for continuation transfers.

http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-transport-v1.0.html#type-transfer

Which seems to imply that it's not required for non-multi-transfer messages (EH includes it in neither situation as far as I've seen), thought the same language is used for delivery-id and message-format. I can see why delivery-id and delivery-tag might not be necessary for non-multi-transfer deliveries, but I don't see why message-format would be required for one but not the other. My conclusion is that all three are required for the first transfer of a message and the language regarding multi-transfers is only to call out that they need not be included in the subsequent continuation transfers.

I'm willing to omit these checks as I don't think they're worth breaking EH support for, but I would like to understand if this is intentional, a bug in EH, or if I'm misinterpreting the spec. Any help you can provide is appreciated.

**Comment by devigned** [comment]
Thank you for the heads up, @vcabbage. I'm going to tag some Event Hub folks and see if we can sort this out.

@sjkwak and @jfggdl can you comment this functionality?

**Comment by devigned** [comment]
Per @xinchen10,
> Event Hubs send all transfers settled with an empty (not null) delivery tag. It is protocol compliant.

**Comment by vcabbage** [comment]
@devigned @xinchen10 Thank you! I jumped to the wrong conclusion. The actual problem is that my decoding is flawed. A zero length binary value is currently being decoded as null.

**Pull request merged**
