### PR TITLE
Add map and slice unmarshalling

### PR DESCRIPTION
**Pull request by amenzhinsky**
Trying to make this driver work with azure iot hub, right now facing problem that message `Value` cannot be parsed.

Started working on missing datatypes and added `[]string`, `[][]bytes` and `[]uint32` to start with, looks kind of ugly now. Probably it worth trying to use the reflect magic here.

Any advice on this? 
Thanks in advance.

### CODE REVIEW

**Comment by vcabbage** [comment]
I'll need to spend some time thinking about how to fit this support in with the reset of the library.

I really appreciate the contributions. For larger changes like this I'd like people to open an issue first. The entire library is still in a state of flux and working out some of the details of marshaling/unmarshaling the non-scalar types is something I still need to figure out myself.

**Comment by amenzhinsky** [comment]
Sure, no problem. #21

**Comment by amenzhinsky** [comment]
As an option it's can be implemented like in the `json` package:
```go
type encoder func(w writer, v reflect.Value) error

func encode(w writer, v interface{}) ([]byte, error) {
	return valueEncoder(reflect.ValueOf(v))(w, v)
}

func valueEncoder(v reflect.Type) (encoder, error) {
	switch k: = v.Kind() {
	case reflect.Int8:
		return encodeInt8, nil
	// ...
	default:
		return nil, fmt.Errorf("%s is not supported", k.String())
	}
}
```

**Comment by vcabbage** [comment]
I want to avoid reflection as much as is reasonable as it makes the code harder to follow and tends to be slower. The `json` package has to deal with user created structures, I don't think that's the case here. Even if it does end up being the case, I think the common cases can use type specific implementations and perhaps resort to reflection where necessary.

I'm going to close this PR since I'd like to go with the approach I've been working on in the `more-types` branch.

**Comment by amenzhinsky** [comment]
Thanks that's great!
I'll test your branch when I get a chance and leave a feedback here if I find something.

**Pull request closed without merging**
